# Generated by Django 5.2.7 on 2025-11-13 12:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categorii_icon/')),
            ],
        ),
        migrations.CreateModel(
            name='Depozit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('adresa', models.TextField()),
                ('oras', models.CharField(max_length=200)),
                ('activ', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=50)),
                ('descriere', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('adresa_livrare', models.TextField(blank=True, null=True)),
                ('abonat_newsletter', models.BooleanField(default=False)),
                ('data_inregistrare', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Articol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='produse/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='MarimeArticol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.articol')),
                ('marime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.marime')),
            ],
            options={
                'unique_together': {('marime', 'articol')},
            },
        ),
        migrations.AddField(
            model_name='articol',
            name='marimi',
            field=models.ManyToManyField(through='aplicatie.MarimeArticol', to='aplicatie.marime'),
        ),
        migrations.CreateModel(
            name='Stoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField()),
                ('actualizat', models.DateTimeField(auto_now=True)),
                ('articol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.articol')),
                ('depozit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.depozit')),
            ],
        ),
        migrations.CreateModel(
            name='VanzariZilnice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('cantitate', models.IntegerField()),
                ('venit_total', models.IntegerField()),
                ('articol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie.articol')),
            ],
        ),
    ]
